#!/usr/bin/env node
/**
 * Build script for VYRO VPN
 * Creates vyro-vpn-full-project.zip and generates base64 file for client-side download
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

const EXCLUDE_PATTERNS = [
  'node_modules',
  'dist',
  'build',
  '.git',
  '.vite',
  'coverage',
  '*.log',
  '.DS_Store',
  'vyro-vpn-full-project.zip',
];

function shouldExclude(filePath) {
  const relative = path.relative(rootDir, filePath);
  return EXCLUDE_PATTERNS.some(pattern => {
    if (pattern.includes('*')) {
      const regex = new RegExp(pattern.replace('*', '.*'));
      return regex.test(relative);
    }
    return relative.includes(pattern);
  });
}

function getAllFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);
  
  files.forEach(file => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    
    if (shouldExclude(filePath)) {
      return;
    }
    
    if (stat.isDirectory()) {
      getAllFiles(filePath, fileList);
    } else {
      // Skip the generated base64 file itself to avoid circular reference
      // We'll include a placeholder and then regenerate
      if (filePath.includes('projectZipBase64.ts')) {
        return;
      }
      fileList.push(filePath);
    }
  });
  
  return fileList;
}

async function createZip() {
  console.log('📦 Building VYRO VPN project archive...\n');
  
  try {
    // Use zip command if available, otherwise use Node.js implementation
    const zipPath = path.join(rootDir, 'vyro-vpn-full-project.zip');
    
    // Remove old zip
    if (fs.existsSync(zipPath)) {
      fs.unlinkSync(zipPath);
      console.log('🗑️  Removed old archive');
    }
    
    // Try using system zip command
    try {
      console.log('📁 Collecting files...');
      const files = getAllFiles(rootDir);
      console.log(`   Found ${files.length} files`);
      
      // Create zip using system command
      const excludeArgs = EXCLUDE_PATTERNS.map(p => `-x "*${p}*"`).join(' ');
      // Also exclude the base64 file to avoid bloat
      const cmd = `cd "${rootDir}" && zip -r vyro-vpn-full-project.zip . -x "node_modules/*" "dist/*" ".git/*" "coverage/*" "*.log" ".DS_Store" "vyro-vpn-full-project.zip" "src/data/projectZipBase64.ts" "bun.lockb" 2>&1 | tail -n 20`;
      
      console.log('🤐 Creating ZIP archive...');
      execSync(cmd, { stdio: 'inherit' });
      
      console.log(`\n✅ ZIP created: ${zipPath}`);
      const stats = fs.statSync(zipPath);
      console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
      
      // Now generate base64
      console.log('\n🔐 Generating Base64 for client-side download...');
      const zipData = fs.readFileSync(zipPath);
      const base64 = zipData.toString('base64');
      
      const base64FilePath = path.join(rootDir, 'src/data/projectZipBase64.ts');
      const base64Content = `/**
 * Auto-generated file - Contains base64 encoded project ZIP
 * Generated by scripts/build-zip.js
 * Size: ${(base64.length / 1024).toFixed(1)} KB base64, ${(zipData.length / 1024).toFixed(1)} KB original
 * Generated: ${new Date().toISOString()}
 * 
 * This file enables 100% client-side ZIP download without server requests,
 * avoiding Cloud Run cookie verification issues on mobile.
 */

export const PROJECT_ZIP_BASE64 = "${base64}";
export const PROJECT_ZIP_SIZE = ${zipData.length};
export const PROJECT_ZIP_GENERATED_AT = "${new Date().toISOString()}";
`;
      
      fs.writeFileSync(base64FilePath, base64Content);
      console.log(`✅ Base64 file generated: ${base64FilePath}`);
      console.log(`   Base64 size: ${(base64.length / 1024).toFixed(1)} KB`);
      
      console.log('\n🎉 Build complete! Project is ready for download.');
      console.log('\n📋 Summary:');
      console.log(`   - ZIP: vyro-vpn-full-project.zip (${(stats.size / 1024).toFixed(1)} KB)`);
      console.log(`   - Base64: src/data/projectZipBase64.ts (${(base64.length / 1024).toFixed(1)} KB)`);
      console.log(`   - Files: ${files.length} files included`);
      
    } catch (zipError) {
      console.log('⚠️  System zip failed, trying alternative method...');
      console.error(zipError.message);
      
      // Fallback: Create a simple archive listing
      const files = getAllFiles(rootDir);
      const placeholder = {
        name: 'vyro-vpn',
        version: '2.5.4',
        files: files.map(f => path.relative(rootDir, f)),
        generated: new Date().toISOString(),
        note: 'This is a placeholder - install zip command for full archive'
      };
      
      fs.writeFileSync(zipPath, JSON.stringify(placeholder, null, 2));
      console.log('📝 Created placeholder archive');
    }
    
  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

createZip();
